### ISSUE TITLE
disqus_id_for don't work in fresh versions of nanoc

### ISSUE THREAD

**Issue by grv87** [aadlani/nanoc-toolbox#7]
I try to use Disqus helper with the following code:

``` ruby
disqus_js_snippet({
    'shortname' => 'example',
    'identifier' => disqus_id_for(@item),
    'title' => @item[:title],
})
```

I get the following error:

```
RuntimeError: can't modify frozen Hash
You attempted to modify immutable data. Some data, such as item/layout attribute
s and raw item/layout content, can not be modified once compilation has started.
 (This was unintentionally possible in 3.1.x and before, but has been disabled i
n 3.2.x in order to allow compiler optimisations.)
```

The problem is in calling disqus_id_for. Either I do something wrong (then please include an example in documentation) or the code should be updated. I'm not a Ruby spec, so can't correct it by myself.

**Comment by aadlani** [comment]
I can't reproduce the bug, I using the exact same snippet with the latest nanoc (https://github.com/aadlani/anouar.adlani.com/blob/master/layouts/article.html.erb#L70) and it does work. Could you please confirm that the issue still exists or explain me how to reproduce it.

**Comment by grv87** [comment]
I'll test it in 4 days and give you feedback.

**Comment by grv87** [comment]
I still have this issue. Versions of nanoc:

```
nanoc 3.7.3 (c) 2007-2014 Denis Defreyne.
Running ruby 1.9.3 (2014-02-24) on i386-mingw32 with RubyGems 1.8.28.
```

and

```
nanoc © 3.7.3  2007-2014 Denis Defreyne.
Running ruby 1.9.3 (2012-04-20) on x86_64-linux with RubyGems 1.8.23.
```

Stack trace (for Windows):

```
0. C:/dev-root/Ruby193/lib/ruby/gems/1.9.1/gems/nanoc-3.7.3/lib/nanoc/base/source_data/item.rb:205:in `[]='
1. C:/dev-root/Ruby193/lib/ruby/gems/1.9.1/gems/nanoc-3.7.3/lib/nanoc/base/source_data/item.rb:205:in `[]='
2. C:/dev-root/Ruby193/lib/ruby/gems/1.9.1/gems/nanoc-toolbox-0.2.1/lib/nanoc/toolbox/helpers/blogging_extra.rb:80:in `slug_for'
3. C:/dev-root/Ruby193/lib/ruby/gems/1.9.1/gems/nanoc-toolbox-0.2.1/lib/nanoc/toolbox/helpers/disqus.rb:18:in `disqus_id_for'
4. layout /default.html/:35:in `get_binding'
5. C:/dev-root/Ruby193/lib/ruby/1.9.1/erb.rb:838:in `eval'
6. C:/dev-root/Ruby193/lib/ruby/1.9.1/erb.rb:838:in `result'
7. C:/dev-root/Ruby193/lib/ruby/gems/1.9.1/gems/nanoc-3.7.3/lib/nanoc/filters/erb.rb:34:in `run'
8. C:/dev-root/Ruby193/lib/ruby/gems/1.9.1/gems/nanoc-3.7.3/lib/nanoc/base/compilation/filter.rb:121:in `setup_and_run'
9. C:/dev-root/Ruby193/lib/ruby/gems/1.9.1/gems/nanoc-3.7.3/lib/nanoc/base/result_data/item_rep.rb:403:in `layout'
... 34 more lines omitted. See full crash log for details.
```

You could look at file https://github.com/FIDATA/fidata.github.io/blob/master/src/layouts/default.html.erb. Change `@item[:disqus_identifier]` to `disqus_id_for(@item)`, and the website in that repository won't get compiled.

**Comment by aadlani** [comment]
Thx for the feedback, I was able to reproduce your issue with the website you referenced.

The Disqus helper expects to be working on "Posts" with certain attributes like `slug`. 
In your [`Rules` file](https://github.com/FIDATA/fidata.github.io/blob/master/src/Rules#L33),  in the `preprocessor` you could use the `BloggingExtra` helper to add the post behavior like described [here](https://github.com/aadlani/nanoc-toolbox/wiki/Blogging-Extra-Helper). You will then prevent your items being modified after compilation.

I tried it locally and it worked fine.
