### ISSUE TITLE
nanoc gist helper docs are incomplete

### ISSUE THREAD

**Issue by jm3** [aadlani/nanoc-toolbox#8]
I've bundled the `nanoc-toolbox` gem, required `nanoc/toolbox` and included `Nanoc::Toolbox::Helpers::GithubGist` in my libraries, and used the syntax: `gist(2669385)` in my markdown file, but nanoc is still emitting the literal "gist(2669385)" in the output instead of generating the JS to embed it.

Did I miss a step?

**Comment by aadlani** [comment]
It seems to be the correct usage, as described here: https://github.com/aadlani/nanoc-toolbox/wiki/Github-Gist-Helper

the `gist(2669385)` call should be done in ruby, that means you should be in erb like `<%= gist(2669385) %>`, and that your .md files are filtered with `erb` (ie: https://github.com/aadlani/anouar.adlani.com/blob/master/Rules#L49)

**Comment by jm3** [comment]
Yeah, the docs didn't mention either of those; I put the gist() call inside an erb expression `<%= tag %>` and made sure `.md` files were being filtered through both kramdown (for Markdown) **and** ERB; for some reason, the Markdown filter needs to come after ERB, which is the opposite of yours.

Fixing those things surfaced a new bug, tho; i'll report it as a new issue.
